/*
 * Sample Application Flow OAuth2 Project
 * This is an example of using OAuth2 Application Flow in a specification to describe security to your API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Server example operation
     *
     * This is an example operation to show how security is applied to the call.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void exampleGetTest() throws ApiException {
        api.exampleGet();

        // TODO: test validations
    }
    
    /**
     * Server heartbeat operation
     *
     * This operation shows how to override the global security defined above, as we want to open it up for all users.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void pingGetTest() throws ApiException {
        api.pingGet();

        // TODO: test validations
    }
    
}
