/*
 * Simple  API
 * This is a simple API with auto mocking enabled
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprakash@nousinfo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse200
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-04T13:12:51.144Z[GMT]")
public class InlineResponse200 {
  @SerializedName("user_name")
  private String userName = null;

  @SerializedName("roles_attributes")
  private String rolesAttributes = null;

  @SerializedName("login_status")
  private String loginStatus = null;

  @SerializedName("userId")
  private String userId = null;

  public InlineResponse200 userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @Schema(description = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public InlineResponse200 rolesAttributes(String rolesAttributes) {
    this.rolesAttributes = rolesAttributes;
    return this;
  }

   /**
   * Get rolesAttributes
   * @return rolesAttributes
  **/
  @Schema(description = "")
  public String getRolesAttributes() {
    return rolesAttributes;
  }

  public void setRolesAttributes(String rolesAttributes) {
    this.rolesAttributes = rolesAttributes;
  }

  public InlineResponse200 loginStatus(String loginStatus) {
    this.loginStatus = loginStatus;
    return this;
  }

   /**
   * Get loginStatus
   * @return loginStatus
  **/
  @Schema(description = "")
  public String getLoginStatus() {
    return loginStatus;
  }

  public void setLoginStatus(String loginStatus) {
    this.loginStatus = loginStatus;
  }

  public InlineResponse200 userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.userName, inlineResponse200.userName) &&
        Objects.equals(this.rolesAttributes, inlineResponse200.rolesAttributes) &&
        Objects.equals(this.loginStatus, inlineResponse200.loginStatus) &&
        Objects.equals(this.userId, inlineResponse200.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, rolesAttributes, loginStatus, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    rolesAttributes: ").append(toIndentedString(rolesAttributes)).append("\n");
    sb.append("    loginStatus: ").append(toIndentedString(loginStatus)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
